# Multiplicação de Matrizes

In [ ]:
import numpy as np

A = np.array([[1, 2],[3, 4],])
B = np.array([[-2, 1],[1.5,-0.5]])
print('A ')
print(A)
print('\nB ')
print(B)
I = np.dot(A, B) # AxB - Se o produto de AxB é uma matriz identidade, B é inverso de A
print('\nIdentidade: ')
print(I)

A 
[[1 2]
 [3 4]]

B 
[[-2.   1. ]
 [ 1.5 -0.5]]

Identidade: 
[[1. 0.]
 [0. 1.]]


Matriz identidade - elemento neutro da multiplicação de Matrizes:

In [ ]:
A2 = np.dot(A, I)
print('A x I :')
print(np.dot(A,I)) # AxI
print('\nB x I :')
print(np.dot(B,I)) # BxI

A x I :
[[1. 2.]
 [3. 4.]]

B x I :
[[-2.   1. ]
 [ 1.5 -0.5]]


# Aplicação prática:
Complete os blocos de código
```
# <implemente>
```

Para enviar uma mensagem criptografada e descriptografar mensagens

In [ ]:
# mensagem

# <implemente: uma mensagem com 10 letras. ex: ['H','E', 'L','L','O','W','O','R','L','D']>
mensagem = ['','', '','','','','','','','']

print(mensagem)

['H', 'E', 'L', 'L', 'O', 'W', 'O', 'R', 'L', 'D']


In [ ]:
# transformando a mensagem em matriz numérica
import string
import numpy as np

letras = list(string.ascii_uppercase)
print(letras)
mensagem_numerica = []
for letra in mensagem:


    # <implemente: para pegar o index (posição) da letra na lista de 'letras'>
    index = 0 # retorna o index da lista na posição da letra


    mensagem_numerica.append(index)
print("\nmensagem numerica:", mensagem_numerica)

# cria matriz de 2 linhas - para ser possivel a multiplicação
matriz_numerica = np.array(mensagem_numerica).reshape(2, -1)
print("\nmatriz:", matriz_numerica)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

mensagem numerica: [7, 4, 11, 11, 14, 22, 14, 17, 11, 3]

matriz: [[ 7  4 11 11 14]
 [22 14 17 11  3]]


In [ ]:
# criptografa a mensagem:  utilizando multiplicação de matrizes (numpy)

# Mensagem criptografada resultado de: A x  matriz_numerica


# <implemente: a multiplicação>



print("Matriz criptografada:\n")

Matriz criptografada:
 [[ 51  32  45  33  20]
 [109  68 101  77  54]]





> - Troque mensagens com um colega para descriptografar uma mensagem diferente❗



In [ ]:
# descriptografando a mensagem - multiplicando mensagem criptografada por matriz B (inversa de A)


# <implemente: a multiplicação>



print("Matriz Descriptografada:\n")

Matriz Descriptografada:
 [[ 7.  4. 11. 11. 14.]
 [22. 14. 17. 11.  3.]]


In [ ]:
# Transforma a mensagem numérica de volta em texto
mensagem_texto = []
for linha in D: # <implemente: o nome matriz Descriptografada>
    for indice in linha:


        # <implemente: para pegar a letra com base no index da mensagem>



        mensagem_texto.append(letra)
print("Mensagem Descriptografada:\n", mensagem_texto)

Mensagem Descriptografada:
 ['H', 'E', 'L', 'L', 'O', 'W', 'O', 'R', 'L', 'D']
